### ISSUE TITLE
mlgents bug

### ISSUE THREAD

**Issue by highmlow** [mbaske/angry-ai#3]
![bug](https://user-images.githubusercontent.com/77030103/103710877-7434cb00-4ff9-11eb-903b-8920fb7f4ade.PNG)

There are too many errors when I brought the mlagent 0.12.0 version and used it. So, using the 0.8.1 version reduced the error. But I don't know why there is an error like a screenshot. Could you tell me how to solve it?

**Comment by mbaske** [comment]
Hi, please try with this branch https://github.com/mbaske/angry-ai/tree/Pre-0.12
It has a slightly older version, including the ML-Agents files.

**Comment by highmlow** [comment]
I could solve it thanks to your advice. Thank you so much for sharing. Have a nice day!!
